<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Cata;
use Carbon\Carbon;


class CataSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        Cata::insert([
            [
                'titulo' => 'La Redonda',
                'descripcion' => '<ul class="list-disc list-inside text-xs"><li>ROSADO SEMI SECO</li><li>BLANCO DULCE</li><li>NOSOTROS SEMI DULCE</li></ul>',
                'salon' => 'Amarillo',
                'logo' => 'logo-03',
                'expositor' => 'Adrian Roa',
                'fecha_hora' => Carbon::create(2025,8,2)->setTime(13,0),
                'capacidad' => 24,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'titulo' => 'La Puerta del Sol',
                'descripcion' => '',
                'salon' => 'Troje',
                'logo' => 'logo-19',
                'expositor' => 'Luis Alberto Martinez',
                'fecha_hora' => Carbon::create(2025,8,2)->setTime(13,0),
                'capacidad' => 24,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'titulo' => 'Viña Concha y Toro',
                'descripcion' => '',
                'salon' => 'Rojo',
                'logo' => 'logo-11',
                'expositor' => 'Viridiana Mosqueda',
                'fecha_hora' => Carbon::create(2025,8,2)->setTime(13,0),
                'capacidad' => 20,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'titulo' => 'Cesarfer',
                'descripcion' => '<ul class="list-disc list-inside text-xs"><li>VINO NOZECO</li></ul>',
                'salon' => 'Amarillo',
                'logo' => '',
                'expositor' => 'Paola Cruz Villanueva',
                'fecha_hora' => Carbon::create(2025,8,2)->setTime(14,0),
                'capacidad' => 40,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'titulo' => 'Unique Wines',
                'descripcion' => '<ul class="list-disc list-inside text-xs"><li>SAN MIGUEL</li></ul>',
                'salon' => 'Troje',
                'logo' => '',
                'expositor' => 'Carlos Alberto Martinez',
                'fecha_hora' => Carbon::create(2025,8,2)->setTime(14,0),
                'capacidad' => 24,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'titulo' => 'La Redonda',
                'descripcion' => '<ul class="list-disc list-inside text-xs"><li>ROSADO SEMI SECO</li><li>BLANCO DULCE</li><li>NOSOTROS SEMI DULCE</li></ul>',
                'salon' => 'Amarillo',
                'logo' => 'logo-03',
                'expositor' => 'Adrian Rua',
                'fecha_hora' => Carbon::create(2025,8,2)->setTime(15,0),
                'capacidad' => 24,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'titulo' => 'Productos de Uva',
                'descripcion' => '<ul class="list-disc list-inside text-xs"><li>CHAMPBRULE</li><li>PENINSULA ESPALDERA</li><li>CABERNET RESERVA</li></ul>',
                'salon' => 'Troje',
                'logo' => '',
                'expositor' => 'Fernando Ruiz de Chavez',
                'fecha_hora' => Carbon::create(2025,8,2)->setTime(15,0),
                'capacidad' => 30,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'titulo' => 'Bodegas la negrita',
                'descripcion' => '',
                'salon' => 'Amarillo',
                'logo' => '',
                'expositor' => 'Jonathan Reyes',
                'fecha_hora' => Carbon::create(2025,8,2)->setTime(16,0),
                'capacidad' => 20,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'titulo' => 'La Puerta del Sol',
                'descripcion' => '',
                'salon' => 'Troje',
                'logo' => 'logo-19',
                'expositor' => 'Luis Alberto Martinez',
                'fecha_hora' => Carbon::create(2025,8,2)->setTime(16,0),
                'capacidad' => 24,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'titulo' => 'Viña Concha y Toro',
                'descripcion' => '',
                'salon' => 'Rojo',
                'logo' => 'logo-11',
                'expositor' => 'Viridiana Mosqueda',
                'fecha_hora' => Carbon::create(2025,8,2)->setTime(16,0),
                'capacidad' => 20,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'titulo' => 'La Compañia del Vino',
                'descripcion' => '<ul class="list-disc list-inside text-xs"><li>ROQUETA BLANCO</li><li>TEMPRANILLO</li></ul>',
                'salon' => 'Amarillo',
                'logo' => '',
                'expositor' => 'Hector Ruiz Blanco',
                'fecha_hora' => Carbon::create(2025,8,2)->setTime(17,0),
                'capacidad' => 20,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'titulo' => 'Cesarfer',
                'descripcion' => '<ul class="list-disc list-inside text-xs"><li>RAMON BILBAO</li></ul>',
                'salon' => 'Troje',
                'logo' => '',
                'expositor' => 'Cristopher Bravo',
                'fecha_hora' => Carbon::create(2025,8,2)->setTime(17,0),
                'capacidad' => 40,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'titulo' => 'Monte Xanic',
                'descripcion' => '<ul class="list-disc list-inside text-xs"><li>CALIXA BLEND</li><li>ROSE</li><li>MERLOT</li></ul>',
                'salon' => 'Rojo',
                'logo' => 'logo-16',
                'expositor' => 'Alejandro Arenas',
                'fecha_hora' => Carbon::create(2025,8,2)->setTime(17,0),
                'capacidad' => 20,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'titulo' => 'Moet Hennesy',
                'descripcion' => '<ul class="list-disc list-inside text-xs"><li>MINUTY</li><li>WHISPERING</li></ul>',
                'salon' => 'Amarillo',
                'logo' => 'logo-04',
                'expositor' => 'Javier Lopez',
                'fecha_hora' => Carbon::create(2025,8,2)->setTime(18,0),
                'capacidad' => 25,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'titulo' => 'Agaves',
                'descripcion' => '<ul class="list-disc list-inside text-xs"><li>DOLCE AMORE</li></ul>',
                'salon' => 'Troje',
                'logo' => '',
                'expositor' => 'Juan Antonio Martinez y Alberto Cacelis',
                'fecha_hora' => Carbon::create(2025,8,2)->setTime(18,0),
                'capacidad' => 30,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'titulo' => 'Unique Wine',
                'descripcion' => '<ul class="list-disc list-inside text-xs"><li>TARAPACA</li></ul>',
                'salon' => 'Rojo',
                'logo' => '',
                'expositor' => 'Carlos Alberto Martinez',
                'fecha_hora' => Carbon::create(2025,8,2)->setTime(18,0),
                'capacidad' => 24,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'titulo' => 'La Compañia del Vino',
                'descripcion' => '<ul class="list-disc list-inside text-xs"><li>IZADI RESERVA</li></ul>',
                'salon' => 'Amarillo',
                'logo' => '',
                'expositor' => 'Hector Ruiz Blanco',
                'fecha_hora' => Carbon::create(2025,8,2)->setTime(19,0),
                'capacidad' => 20,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'titulo' => 'Cerveza',
                'descripcion' => '<ul class="list-disc list-inside text-xs"><li>CERVEZA ARTESANAL</li><li>MAESTRO CERVECERO</li></ul>',
                'salon' => 'Troje',
                'logo' => '',
                'expositor' => 'Ivan Rocha',
                'fecha_hora' => Carbon::create(2025,8,2)->setTime(19,0),
                'capacidad' => 30,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
